### PR TITLE
Code Review #5 NYT Project

### PR DESCRIPTION
**Pull request by MarcusAl**
Changed the pull request and location to compare from feature branch (test_project) to main branch. Should now be ready for deployment, and review.

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello team! Good job so far. :smile: I'll mention some details that you need to fix and then you can move on.


- [x] I don't understand what is this. Kindly remove it.



- [x] Please align the sentence with the picture above it.



- [x]  Kindly add some more options to the editor's pick section.



- [x] Your theory of inflation section looks like this at my side. Don't use just one picture. Instead, use separated pictures and position them one by one.



- [x]  You can align the video with the column. You can do this with the picture below it as well.

- [x]  Suggested newsletter for you, more in astronomy and the footer parts needs to decrease in width. Kindly fix them and make it look like the original page.

Your HTML code looks decent and structured. You've mostly used semantic HTML and the aside tag as well. :muscle: Kindly work on the mentioned issues and then submit for a re-review.

- [x] Don't create another PR. Use this PR for the next submission. :smile: 

If you have any questions about the review, feel free to reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by MarcusAl** [comment]
Modified the editors picks section, footer, inflation section, and some other alignments issues. Discussed with the Code Reviewer: 'eypsrcnuygr' the need for the top grey box which is the advertisement section. He acknowledged it and agreed it should stay. This advertisement part is visible on the NYT website as a new visitor. Also agreed to take a screenshot for the inflation section as we could not manually align it across multiple screens.  We used this screenshot instead.

Finally the editors picks we decided to add more image, and we explained this layout is the same layout as the NYT official page, again as a new visitor.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @CacheMeGifYouCan and @denisdiaconu :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [x] Please delete this, just as requested by the previous TSE
image
- [x] The Editor's pick section should have one more item, just like it is on the original page.
- [x] The Editor's pick section should have its text aligned to the right of the images and also centred.
- [x] Elements should be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction))
- [x] You're not allowed to use one screenshot or image for the whole of the **Theory of Inflation** section.

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by MarcusAl** [comment]
Code Review #6 NYT Project

We removed the image at the top of the page.
The Editor's pick section has one more item, and we fixed his position.
We used the combination of all three techniques(float, flex, and grid) for the elements.
We removed the image of the Theory of inflation section, and we used flex instead on it. We added individual captions for each image.

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 
Hello, @CacheMeGifYouCan  very nice project 👍🏿 you are almost there. However, there are a few changes that need to be done. Kindly check below ⬇️ 

- [x] The alignment of this section is wrong ⬇️  you have aligned it vertically and it should be horizontally aligned.
### yours
centering elements yours

### original
centering elements

- [x] Files that are not part of the project should be added to .gitignore. 
gitignore

Kindly fix the above issue and submit the project for another review.

### if you have any question reach me on slack @peterrobert

### HAPPY CODING 💻

**Comment by MarcusAl** [comment]
Code Review #7 NYT Project

Modified the 'unlock content' section to be horizontal. Removed unnecessary files from the commit.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @denisdiaconu 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ]  MIT license is not working in the readme file
- [x] Align in the center 
Image


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by denisdiaconu** [comment]
We fixed the MIT link and we aligned the article in the center of the page.

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @CacheMeGifYouCan and @denisdiaconu ! 👋 👋 


### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

**Optional**
- [ ] For future references, use [font awesome](https://fontawesome.com/v4.7.0/icons/) for the icons on the page, especially the footer.
- [ ] Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to determine the font family and sizes used in the actual site.
- [ ] Use [this](https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp?hl=en-GB) SVG picker for SVG images for future reference.

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
